services:
  - type: web
    name: iris-classifier
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    branch: main